Exercise on Functions:

Task - 1

In [2]:
def convert_units():
    """
    Converts units of length, weight, and volume.

    Prompts the user to select conversion type and value,
    performs the conversion, and prints the result.

    Returns:
        None
    """
    try:
        print("Choose conversion type: length, weight, volume")
        conversion_type = input("Enter conversion type: ").lower()

        value = float(input("Enter value to convert: "))

        if conversion_type == "length":
            print("Options: m_to_ft or ft_to_m")
            option = input("Choose option: ")

            if option == "m_to_ft":
                result = value * 3.28084
                print("Result:", result, "ft")

            elif option == "ft_to_m":
                result = value * 0.3048
                print("Result:", result, "m")

            else:
                print("Invalid length conversion")

        elif conversion_type == "weight":
            print("Options: kg_to_lbs or lbs_to_kg")
            option = input("Choose option: ")

            if option == "kg_to_lbs":
                result = value * 2.20462
                print("Result:", result, "lbs")

            elif option == "lbs_to_kg":
                result = value * 0.453592
                print("Result:", result, "kg")

            else:
                print("Invalid weight conversion")

        elif conversion_type == "volume":
            print("Options: l_to_gal or gal_to_l")
            option = input("Choose option: ")

            if option == "l_to_gal":
                result = value * 0.264172
                print("Result:", result, "gal")

            elif option == "gal_to_l":
                result = value * 3.78541
                print("Result:", result, "L")

            else:
                print("Invalid volume conversion")

        else:
            print("Unsupported conversion type")

    except ValueError:
        print("Invalid input! Please enter numeric value.")


convert_units()

Choose conversion type: length, weight, volume
Enter conversion type: weight
Enter value to convert: 69
Options: kg_to_lbs or lbs_to_kg
Choose option: kg_to_lbs
Result: 152.11878 lbs


Task-2

In [45]:
def calculate_sum(numbers):
    """Returns the sum of the numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of the numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns the maximum number."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum number."""
    return min(numbers)


try:
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    if len(nums) == 0:
        raise ValueError("List cannot be empty")

    operation = input("Choose operation (sum, avg, max, min): ")

    if operation == "sum":
        print("Sum:", calculate_sum(nums))

    elif operation == "avg":
        print("Average:", calculate_average(nums))

    elif operation == "max":
        print("Maximum:", find_max(nums))

    elif operation == "min":
        print("Minimum:", find_min(nums))

    else:
        print("Invalid operation")

except ValueError:
    print("Invalid input! Please enter numbers.")

Enter numbers separated by space: 56 78
Choose operation (sum, avg, max, min): max
Maximum: 78.0


4.2 Exercise on List Manipulation

1 Extract Every Other Element

In [1]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2 Slice a Sublist

In [3]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3 Reverse List

In [4]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4 Remove First and Last

In [5]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5 Get First n Elements

In [6]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6 Get Last n Elements

In [7]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


7 Reverse Skip

In [8]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


4.3 Exercise on Nested List

1 Flatten Nested List

In [9]:
def flatten(lst):
    result = []
    for i in lst:
        if isinstance(i,list):
            result.extend(i)
        else:
            result.append(i)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2 Access Nested Element

In [10]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


3 Sum Nested List

In [11]:
def sum_nested(lst):
    total = 0
    for i in lst:
        if isinstance(i,list):
            total += sum_nested(i)
        else:
            total += i
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


4 Remove Element from Nested List

In [12]:
def remove_element(lst, elem):
    result = []
    for i in lst:
        if isinstance(i,list):
            result.append([x for x in i if x != elem])
        elif i != elem:
            result.append(i)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5 Find Maximum in Nested List

In [13]:
def find_max(lst):
    max_val = float('-inf')
    for i in lst:
        if isinstance(i,list):
            max_val = max(max_val, find_max(i))
        else:
            max_val = max(max_val, i)
    return max_val

print(find_max([[1,2],[3,[4,5]],6]))

6


6 Count Occurrences

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for i in lst:
        if isinstance(i,list):
            count += count_occurrences(i,elem)
        elif i == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

7 Deep Flatten

In [14]:
def deep_flatten(lst):
    result = []
    for i in lst:
        if isinstance(i,list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8 Nested Average

In [15]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5



 Problem-1 Array Creation

In [2]:
#1
import numpy as np
arr = np.empty((2,2))
print(arr)

[[3.5566288e-315 0.0000000e+000]
 [9.0411522e+271 1.0212402e+277]]


In [3]:
#2
import numpy as np

arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
#3
import numpy as np

arr = np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
#4
import numpy as np

a = np.array([[1,2],[3,4]])
zeros_arr = np.zeros_like(a)
print(zeros_arr)

[[0 0]
 [0 0]]


In [6]:
#5
import numpy as np

a = np.array([[1,2],[3,4]])
ones_arr = np.ones_like(a)
print(ones_arr)

[[1 1]
 [1 1]]


In [7]:
#6
import numpy as np

new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


Problem-2 Array Manipulation
Numerical ranges and Array Indexing.

In [8]:
#1
import numpy as np

arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#2
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#3
import numpy as np

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#4
import numpy as np

arr = np.random.random(30)
print(arr)
print("Mean:", arr.mean())

[0.36526957 0.22736811 0.82575922 0.70859122 0.50785858 0.67863672
 0.53812516 0.41795491 0.29254508 0.56750873 0.42471443 0.78571208
 0.73576225 0.61477633 0.68190718 0.41027242 0.42866021 0.8875001
 0.11755652 0.84307665 0.35943253 0.12118593 0.61310594 0.18894181
 0.87808242 0.29013982 0.86416068 0.17247303 0.66046924 0.64098931]
Mean: 0.5282845391583446


In [12]:
#5
import numpy as np

arr = np.random.random((10,10))
print(arr)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

[[0.79160415 0.10658647 0.56162007 0.98883165 0.8069193  0.21093721
  0.48428424 0.66223516 0.03521919 0.70022563]
 [0.47586883 0.20929333 0.82178379 0.39914894 0.74648425 0.99690326
  0.51876917 0.41839959 0.99644375 0.2401717 ]
 [0.30645506 0.29484038 0.24320699 0.48790108 0.35411357 0.65992692
  0.59548643 0.8428323  0.33278025 0.32980661]
 [0.07234789 0.41234904 0.86332643 0.85744295 0.25876712 0.31004241
  0.04757967 0.20783579 0.28342714 0.27104009]
 [0.89882051 0.72499744 0.93619911 0.85684514 0.01449778 0.87024677
  0.36300794 0.0348428  0.00186773 0.81213916]
 [0.1705049  0.88384301 0.18074691 0.76239691 0.10646763 0.49528233
  0.33552965 0.88761779 0.75603988 0.69142326]
 [0.90765494 0.74973594 0.88168306 0.51948487 0.62815014 0.17558541
  0.20238725 0.6043053  0.15749149 0.28974974]
 [0.14265699 0.01117137 0.14313453 0.76204591 0.79575462 0.66615747
  0.30426894 0.9244818  0.24316147 0.67926856]
 [0.87684678 0.80125673 0.32547495 0.24585503 0.09486931 0.43978904
  0.99238071

In [13]:
#6
import numpy as np

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7
import numpy as np

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

[0 4 0 0 2 1]


In [16]:
#8
import numpy as np

arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#9
import numpy as np

checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem-3 Array Operations

In [18]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [19]:
#!
print(x + y)

[[ 6  8]
 [10 13]]


In [20]:
#2
print (x-y)

[[-4 -4]
 [-4 -3]]


In [21]:
#3
print (x * 3)

[[ 3  6]
 [ 9 15]]


In [22]:
#4
print (x ** 2)

[[ 1  4]
 [ 9 25]]


In [23]:
#5
print ("v.w =", np.dot(v,w))
print ("x.v =", np.dot(x,v))
print ("x.y =", np.dot(x,y))

v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]


In [24]:
#6
print("Row Concatenation:")
print(np.vstack((x,y)))
print ("Column Concatenation:")
print (np.column_stack((v,w)))

Row Concatenation:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column Concatenation:
[[ 9 11]
 [10 12]]


In [25]:
#7
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem-4 Matrix Operations

In [26]:
import numpy as np
A = np.array([[3,4],[7,8]])
B =np.array([[5,3],[2,1]])

In [27]:
#1
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [28]:
#2
print("AB =")
print(np.dot(A,B))
print("BA =")
print(np.dot(B,A))

AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]


In [29]:
#3
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Solve Linear Equation Using Inverse Method

In [31]:
import numpy as np

A = np.array ([[2,-3,1],
               [1,-1,2],
               [3,1,-1]])
B = np.array([-1,-3,9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution (x,y,z):", x)


Solution (x,y,z): [[1 2]
 [3 5]]


Element-wise Addition

Python Lists

In [32]:
#1
import time

size = 1000000
a = list(range(size))
b = list(range(size))
start = time.time()
c = [a[i] + b[i]for i in range(size)]
end = time.time()
print("Python list addition time:", end - start)

Python list addition time: 0.20067930221557617


NumPy Arrays

In [35]:
#2
import numpy as np
import time

size = 1000000
a = np.arange(size)
b = np.arange(size)
start = time.time()
c=a+b
end = time.time()
print("Numpy addition time:", end - start)

Numpy addition time: 0.025677204132080078


Element-wise Multiplication

Python Lists

In [38]:
import time

size = 1000000
a = list(range(size))
b= list(range(size))
start = time.time()
c= [a[i] * b[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end - start)

Python list multiplication time: 0.14571189880371094


NumPy Arrays

In [39]:
import numpy as np
import time

size = 1000000
a = np.arange(size)
b = np.arange(size)
start = time.time()
c = a * b
end = time.time()
print("NumPy multiplication time:", end - start)

NumPy multiplication time: 0.020787477493286133


Dot Products

Python Lists

In [40]:
import time
size = 1000000

a = list(range(size))
b = list(range(size))
start = time.time()
dot = sum(a[i] * b[i] for i in range(size))
end = time.time()
print("Python dot product time:", end - start)

Python dot product time: 0.21840643882751465


NumPy Arrays

In [41]:
import numpy as np
import time

size = 1000000
a = np.arange(size)
b = np.arange(size)
start = time.time()
dot = np.dot(a,b)
end = time.time()
print("NumPy dot product time:", end - start)

NumPy dot product time: 0.0022072792053222656


Matrix Multiplication

Python Lists

In [42]:
import time
import random

size = 100
A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]
result = [[0]*size for _ in range(size)]
start = time.time()
for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]
end = time.time()
print("Python matrix multiplication time:", end - start)

Python matrix multiplication time: 0.21586918830871582


NumPy Arrays

In [43]:
import numpy as np
import time

size = 100
A = np.random.random((size,size))
B = np.random.random((size,size))
start = time.time()
C = np.dot(A,B)
end = time.time()
print("NumPy matrix multiplication time:", end - start)

NumPy matrix multiplication time: 0.0010280609130859375
